main/urls.py
from django.urls import path
from django.conf.urls import include
from main import views


urlpatterns = [
        path('', views.IndexView.as_view(), name='index'),
        path('query/<page_number>', views.QueryView.as_view(), name='query'),
        path('info', views.InfoView.as_view(), name='info'),
]

ocr_site/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from ocr_site import settings
from main.admin import admin_site


urlpatterns = [
    path('admin/', admin_site.urls),
    path('', include(('main.urls', 'main'), namespace='main')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns += staticfiles_urlpatterns()

handler404 = 'main.views.handler404'
handler500 = 'main.views.handler500'

main/models.py
from django.db import models
from django.contrib.sessions.models import Session
from ocr_site.settings import MEDIA_ROOT
from PIL import Image
import pytesseract
import cv2
import numpy as np
import os


LANG_CHOICES = (
    ('rus', 'русский'),
    ('eng', 'english')
)


class ImageUpload(models.Model):
    image = models.ImageField(upload_to="images")
    lang = models.CharField(default="", max_length=15 , choices=LANG_CHOICES)

    def delete(self, *args, **kwargs):
        if os.path.isfile(self.image.path):
            os.remove(self.image.path)
        super(ImageUpload, self).delete(*args,**kwargs)

    def image_to_text(self):
        self.img = MEDIA_ROOT + '/' + str(self.image)
        self.img = cv2.imread(self.img)
        self.img = cv2.resize(self.img, None, fx=1.5, fy=1.5, interpolation=cv2.INTER_CUBIC)
        self.img = cv2.cvtColor(self.img, cv2.COLOR_BGR2GRAY)

        self.kernel = np.ones((1, 1), np.uint8)
        self.img = cv2.dilate(self.img, self.kernel, iterations=1)
        self.img = cv2.erode(self.img, self.kernel, iterations=1)
        self.img = cv2.threshold(cv2.GaussianBlur(self.img, (5, 5), 0), 0, 255, cv2.THRESH_BINARY + cv2.THRESH_OTSU)[1]

        self.text = pytesseract.image_to_string(self.img, lang=self.lang)
        return self.text


class UserQuery(models.Model):
    session = models.ForeignKey(Session, on_delete=models.CASCADE)
    text = models.TextField()
    date = models.DateTimeField(auto_now_add=True)

main/forms.py
from django import forms
from .models import ImageUpload


class UploadForm(forms.ModelForm):
    class Meta:
        model = ImageUpload
        fields = ['image', 'lang']
        labels = {
            'lang':'Язык',
            'image':''
        }
        widgets = {
            'image': forms.FileInput(
                attrs={
                    'style': 'display: none',
                    'class': 'file-input'
                }
            ),
            'lang': forms.Select(
                attrs={
                    'class': 'custom-select col-sm-4'
                }
            )
        }

main/views.py
from django.shortcuts import render, redirect, render_to_response
from django.http import JsonResponse
from django.views.generic import View, CreateView
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.contrib.sessions.models import Session
from .forms import UploadForm
from .models import ImageUpload, UserQuery


class IndexView(View):

    template_name = 'index.html'

    def get(self, request):
        request.session.set_expiry(7*24*60*60)
        request.session['sessionid'] = True
        form = UploadForm()
        args = {"form": form}
        return render(request, self.template_name, args)

    def post(self, request):
        form = UploadForm(self.request.POST, self.request.FILES)
        response_data = {}
        if form.is_valid():
            instance = form.save(commit=False)
            instance.save()
            text = instance.image_to_text()

            save_text = UserQuery(
                session = Session.objects.get(session_key=request.COOKIES.get('sessionid')),
                text = text
                )
            instance.delete()
            if len(save_text.text) > 0:
                save_text.save()
                return JsonResponse({'text': save_text.text})
            else:
                return JsonResponse({'text': 'Не удалось распознать изображение'})
        else:
            return JsonResponse({'text': 'Файл поврежден или не является изображением' })




class QueryView(View):

    template_name = 'query.html'

    def get(self, request, page_number):
        query = UserQuery.objects.filter(session=request.COOKIES.get('sessionid')).order_by('-date')
        if query.count() != 0:
            query_page = Paginator(query, 3)
            try:
                pages = query_page.page(page_number)
            except PageNotAnInteger:
                pages = query_page.page(1)
            except EmptyPage:
                pages = query_page.page(query_page.num_pages)
            args = {"query": pages}
        else:
            args = {"none": "Нет записей"}
        return render(request, self.template_name, args)




class InfoView(View):

    template_name = 'info.html'

    def get(self, request):
        return render(request, self.template_name)









def handler404(request):
    response = render_to_response('404.html')
    response.status_code = 404
    return response


def handler500(request):
    response = render_to_response('500.html')
    response.status_code = 500
    return response

main/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>OCR App</title>
  {% load staticfiles %}
  <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}" type="text/css">
  <link rel="stylesheet" href="{% static 'css/style.css' %}" type="text/css">
  <link rel="stylesheet" href="{% static 'css/mdb.css' %}" type="text/css">
  <link rel="stylesheet" href="{% static 'css/bootstrap-social.css' %}" type="text/css">
  <link rel="stylesheet" href="{% static 'css/font-awesome.css' %}" type="text/css">
  <link rel="stylesheet" href="{% static 'css/docs.css' %}" type="text/css">
  <link rel="shortcut icon" href="{%  static 'images/favicon.ico' %}">
</head>
<body>
  <header>
    <nav class="navbar navbar-light navbar-expand-sm fixed-top bg-info">
		  <a><img src="{% static 'images/logo.png' %}" width="50" height="50"></a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar1" aria-controls="navbar1" aria-expanded="false" aria-label="Toggle navigation">
    	   <span class="navbar-toggler-icon"></span>
  	   </button>
		  <div class="collapse navbar-collapse" id="navbar1">
			   <ul class="navbar-nav navbar-right">
           <li class="nav-item active mr-2 ml-2 mb-1 mt-1">
             <a class="nav-link text-center" href="{% url 'main:index' %}">На главную</a>
           </li>
           <li class="nav-item active mr-2 ml-2 mb-1 mt-1">
             <a class="nav-link text-center" href="{% url 'main:query' page_number=1 %}">Мои запросы</a>
            </li>
            <li class="nav-item active mr-2 ml-2 mb-1 mt-1">
              <a class="nav-link text-center" href="{% url 'main:info' %}">О проекте</a>
            </li>
		   	</ul>
		  </div>
	  </nav>
  </header>
  <div id="main">
    <div id="pg-main">
      {% block content %}
      {% endblock %}
    </div>
    <footer class="footer">
    <div id="foot" class="page-footer font-small grey darken-2">
      <div class="footer-copyright text-center py-3">
        <a class="text-light">© 2018 Copyright:</a>
        <a class="text-light">Дубровин Иван</a>
        <a class="btn btn-social-icon btn-github" href="https://github.com/IvanDubrowin">
          <span class="fa fa-github"></span>
        </a>
      </div>
    </div>
  </footer>
  </div>
  <script type="text/javascript" src="{% static 'js/jquery.js' %}"></script>
  <script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>
  <script type="text/javascript" src="{% static 'js/main.js' %}"></script>
  <script src="{% static 'js/jquery.cookie.js' %}"></script>
  <script src="{% static 'js/validator.min.js' %}"></script>
</body>
</html>

main/templates/index.html
{% extends "base.html" %}
{% block content %}
{% load staticfiles%}
<div id="index" class="container">
  <div id="index-card" class="card text-center">
    <div class="card-header">
      <h5>Загрузка изображения</h5>
    </div>
    <div class="card-body">
      <form id="upload-form" method="post" enctype="multipart/form-data">
        {% csrf_token %}
            <div class="input-group justify-content-center">
              <div id="error-field"></div>
              <label class="input-group-btn">
                <span class="btn btn-outline-success">
                  <h5 class="mt-2">Загрузить</h5>
                  {{ form.image }}
                  <input id="file-image" type="text" class="form-control" readonly>
                </span>
              </label>
            </div>
            <div class="row mb-3">
              <div class="col-sm-4"></div>
              <div class="col-sm-4">
                <div class="progress">
                  <div class="progress-bar" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100" style="width: 0%;"></div>
                </div>
              </div>
              <div class="col-sm-4"></div>
            </div>
            <div class="mb-4">
              {{ form.lang }}
            </div>
      <input id="submit-btn" type="submit" class="btn btn-outline-success" value="Распознать"></input>
      </form>
    </div>
  </div>
  <div id="index-card" class="card text-center">
    <div class="card-header">
      <h5>Распознанный текст</h5>
    </div>
    <div class="card-body">
      <textarea id="text_area" class="form-control" rows="14"></textarea>
    </div>
  </div>
</div>
{% endblock %}

main/templates/info.html
{% extends "base.html" %}
{% block content %}
{% load staticfiles%}
<div id="index" class="container">
  <div id="index-card" class="card text-center">
    <div class="card-header">
    <h5>О проекте</h5>
    </div>
    <div class="card-body">
      <h3>Стек технологий этого сайта:</h3>
      <div class="container">
        <div class="row mb-3">
          <div class="col-md-3">
          </div>
          <div class="col-md-3">
            <a><img src="{% static 'images/django.png' %}" width="50" height="50"></a>
            <h5>Django</h5>
          </div>
          <div class="col-md-3">
            <a><img src="{% static 'images/uwsgi.png' %}" width="80" height="30"></a>
            <h5>UWSGI</h5>
          </div>
          <div class="col-md-3">
          </div>
        </div>
        <div class="row mb-3">
          <div class="col-md-3">
          </div>
          <div class="col-md-3">
            <a><img src="{% static 'images/nginx.png' %}" width="50" height="50"></a>
            <h5>Nginx</h5>
          </div>
          <div class="col-md-3">
            <a><img src="{% static 'images/postgre.png' %}" width="50" height="50"></a>
            <h5>PostgreSQL</h5>
          </div>
          <div class="col-md-3">
          </div>
        </div>
        <div class="row mb-3">
          <div class="col-md-3">
          </div>
          <div class="col-md-3">
            <a><img src="{% static 'images/tesseract.png' %}" width="80" height="50"></a>
            <h5>Tesseract OCR</h5>
          </div>
          <div class="col-md-3">
            <a><img src="{% static 'images/boot.png' %}" width="50" height="50"></a>
            <h5>Bootstrap</h5>
          </div>
          <div class="col-md-3">
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

main/templates/query.html
{% extends "base.html" %}
{% block content %}
{% load staticfiles%}
<div id="index" class="container">
  {% if none %}
  <div id="index-card" class="card text-center">
    <div class="card-body">
      <a>Нет записей</a>
    </div>
  </div>
  {% else %}
  <div id="pg" class="pagination justify-content-center mb-4">
      <ul class="pagination bg-light pagination-circle pg-blue mb-0">
          {% if query.has_previous %}
            <li class="page-item"><a class="page-link" href="{{ query.previous_page_number }}">Назад</a></li>
          {% else %}
            <li class="page-item disabled"><a class="page-link" href="">Назад</a></li>
          {% endif %}
          {% if query.number|add:'-4' > 1 %}
            <li href="{{ query.number|add:'-5' }}">&hellip;</li>
          {% endif %}
          {% for page in query.paginator.page_range %}
            {% if query.number == page %}
              <li class="page-item active"><a class="page-link" href="{{ page }}">{{ page }}</a></li>
            {% elif page > query.number|add:'-3' and page < query.number|add:'3' %}
              <li class="page-item"><a class="page-link" href="{{ page }}">{{ page }}</a></li>
            {% endif %}
          {% endfor %}
          {% if query.paginator.num_pages > query.number|add:'4' %}
            <li href="{{ query.number|add:'5' }}">&hellip;</li>
          {% endif %}
          {% if query.has_next %}
              <li class="page-item"><a class="page-link" href="{{ query.next_page_number }}">Вперед</a></li>
          {% else %}
            <li class="page-item disabled"><a class="page-link" href="">Вперед</a></li>
          {% endif %}
      </ul>
  </div>
  {% for item in query %}
  <div id="index-card" class="card text-center">
    <div class="card-header">
    <h5>{{ item.date }}</h5>
    </div>
    <div class="card-body">
      <a>{{ item.text }}</a>
    </div>
  </div>
  {% endfor %}
  {% endif %}
</div>
{% endblock %}